version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - npm config set '//registry.npmjs.org/:_authToken' $(aws ssm get-parameter --name npm-publish-token --with-decryption --query Parameter.Value)
      - npm publish --access public
